language: scala
sudo: false
jdk: oraclejdk8
scala: 2.12.4
script: sbt scripted

cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/boot/
  - $HOME/.zinc

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete
